### ISSUE TITLE
Trying connect to server but KCP Disconnect.

### ISSUE THREAD

**Issue by csritter** [joaoborks/unity-gamelift-mirror-sample#1]
Hi! I'm trying to connect a remote fleet in aws gamelift server.
I attach the built in a fleet and try to run the Client build.
So after trying to connect, the client can't connect with server.

I trying to put ports like, 7777, 7000-8000, 7500-8500, and not sucessfull.
![image](https://user-images.githubusercontent.com/73347739/119883396-e143f100-bf05-11eb-8ec1-f43f3be2b686.png)

Log:
```
KcpConnection: sending Handshake to other end!
KCP Connection: Disconnected.

```
I tested local and it's working fine.
Do you know what I missing?

(Btw, when i download the project, the samples has missing meshes, but I fixing reimport)

**Comment by csritter** [comment]
Sorry, I dont put UDP too on the port, so I closing this issue!

**Comment by Ahmed1232** [comment]
Hey, I'm running into this issue, can you please elaborate how you solved this?
Thanks
