### ISSUE TITLE
cannot link AWSSDK DLLs in Unity

### ISSUE THREAD

**Issue by peszekeres** [joaoborks/unity-gamelift-mirror-sample#3]
Hi Joao,
I can make the project work but only by a small workaround.
Somehow the client side AWSSDK DLL files are not refered, the compiler does not recognize the Amazon namespace. The only way I could make it work was to install the gamelift amazon plugin from tarball to my project
https://github.com/aws/amazon-gamelift-plugin-unity/releases
By doing so, everything seems to work perfectly, the tarball copies its own DLLs to a Cache directory
The problem is that the client side should be run on an Oculus I ( android ) which dies when
new AmazonGameLiftConfig();
the config is created. This problem doesn`t seem to be unique, after logging the error message I found out that other people suffered the same, for some of them it worked to downgrade the binaries to net standard 2.0 ( as far as I understand, the DLLs coming from the tarball are 4.x compatible )
I have very limited understanding on how linking works, would´t it be just to move the DLLs to the Assets folder?
When installing the tarball, it adds a file
AmazonGameLiftPlugin.Custom.csproj
that contains abs references such as

 <Reference Include="AWSSDK.GameLift">
    <HintPath>C:/Users/Irma/Documents/Peti_cucc/GameLift_Getting_Started/VR_ESCAPE_CITY/Library/PackageCache/com.amazonaws.gamelift@0f847e196504-1644477974832/Runtime/Core/Plugins/AWSSDK.GameLift.dll</HintPath>
    
</Reference>
Thanks for your answer,
And thanks for the sample project + description, its awesome
Peter

**Comment by thatjoaoguy** [comment]
Hi Peter! I'm not sure I fully understand the issue you're having. You said you have to download an additional plugin to make it work but then it wouldn't be built with the game to the target platform, is that right?

It's still very cloudy to me, can you like give more technical details about your Unity project such as:
- Unity Version
- Plugin Folder hierarchy (just the Amazon stuff)
- Are you using Assembly Definitions?
- You said the compiler does not recognize the Amazon namespace, what were you trying to code?
- Did you clone the project and just tried to run it on your target platform, or did you attach the repo to your project?

The binaries included in this repository are already targeting Net Standard 2.0 since, at the time, I was focusing on mobile compatibility. Let's see if we can fix this together.

**Comment by peszekeres** [comment]
Hi Joao!
Thx for your answer!

I wanted to specify exactly what modifications I made on your base project, so I decided to git clone it again and to try to make it work.

Now Im working on an other PC, here everything works like a charm, I git cloned your project and it compiles without any issue, doesnt matter whether I open it with 2020.3 or 2019.4 version of Unity. 

I was confused so I tried to clone and compile your base project to two other PCs and right after cloning and opening in unity ( no modifications were made on my side ) it doesn't compile due to missing references, it cannot find some mirror related stuff, after installing mirror from pkg the namespace 'Amazon' in GameLiftClient.cs cannot be resolved, so to make it work, the AWSSDK plugins have to be installed by hand, seems as if linking were totally messed up.

Is there any Unity setting that might globally effect the process of linking?

On the PC where its working without touching anything, a GameAssemby.DLL is created

It was not the case with my project that I stared to build up on this sample project, however, I dont remember that I modified any setting related to assembling/linking, there the linked DLLs are just copied next to the executable into the folder VR_ESCAPE_CITY_Data/Plugins after compiling

I send you the folder structure of my project anyway
[tree.txt](https://github.com/joaoborks/unity-gamelift-mirror-sample/files/8340706/tree.txt)

Peter

**Comment by peszekeres** [comment]
Hi Joao,
I have recognised that in each case when the project is git cloned, the linking works correctly. However, when its downloaded as a .rar file, for some reason the the linking works differently.
I'm sorry for not being precise, in my previous message I wrote that I used git clone multiple times to get the sample project, I have just realized right now that it was not the case, and in some occasions I just downloaded it as a .rar file.
Nevertheless, I still dont understand exactly what causes this difference in the linking process :D If you have any idea, pls share it with me.
Have a nice day,
Peter

**Comment by peszekeres** [comment]
I compared the git cloned version with the rar version, I found that in the latter one all of the dll-s ( and some other stuff) have the same size. If I open them with a simple text editor, it turns out that these files only contain a reference to git large file storage. So if its not got cloned, then none of the dll-s are downloaded from git large storage, only dummy dlls are present.
